services:
  web:
    build: ./web
    container_name: desafio3-web
    ports:
      - "5000:5000"
    depends_on:
      - db
      - cache
    environment:
      - DB_HOST=db
      - DB_USER=postgres
      - DB_PASSWORD=123
      - DB_NAME=mydb
      - CACHE_HOST=cache
    volumes:
      - ./web:/app
    networks:
      - interna

  db:
    image: postgres:16
    container_name: desafio3-db
    environment:
      POSTGRES_PASSWORD: 123
      POSTGRES_DB: mydb
    networks:
      - interna

  cache:
    image: redis:alpine
    container_name: desafio3-cache
    networks:
      - interna

networks:
  interna:
