services:

  db:
    image: postgres:15
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: pass
      POSTGRES_DB: desafio3
    volumes:
      - pgdata:/var/lib/postgresql/data
    networks:
      - desafio3_net

  cache:
    image: redis:7
    networks:
      - desafio3_net

  web:
    build: ./web
    ports:
      - "8080:3000"
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: pass
      POSTGRES_DB: desafio3
      DB_HOST: db
      REDIS_HOST: cache
    depends_on:
      - db
      - cache
    networks:
      - desafio3_net

volumes:
  pgdata:

networks:
  desafio3_net:
