services:
  service-a:
    build: ./service-a
    container_name: desafio4-service-a
    ports:
      - "5001:5001"

  service-b:
    build: ./service-b
    container_name: desafio4-service-b
    ports:
      - "5002:5002"
    depends_on:
      - service-a