services:
  webserver:
    build: ./server
    container_name: desafio1-webserver
    ports:
      - "8080:8080"
    networks:
      - desafio1_net

  client:
    build: ./client
    container_name: desafio1-client
    depends_on:
      - webserver
    networks:
      - desafio1_net

networks:
  desafio1_net:
    driver: bridge